export const visitSummaryFixture = {
  totalCount: 3,
  checkedCount: 1,
  goodCount: 1,
  cautionCount: 0,
  unconfirmedCount: 2,
};

export const visitDetailFixture = {
  visitId: 31,
  propertyId: 10,
  status: 'IN_PROGRESS',
  startedAt: '2026-08-11T04:00:00Z',
  completedAt: null,
  updatedAt: '2026-08-11T04:00:00Z',
  stages: [
    {
      stage: 'ONLINE_PHONE',
      sourceChecklistId: null,
      checklistName: '전화 확인 사본',
      items: [
        {
          visitItemId: 501,
          origin: 'PROVIDED',
          sourceChecklistItemId: null,
          sourceCheckItemId: 101,
          question: '관리비 포함 항목을 확인했나요?',
          guide: null,
          order: 1,
          status: 'UNCONFIRMED',
          statusVersion: 0,
          statusSavedAt: '2026-08-11T04:00:00Z',
          inlineMemo: '',
          memoVersion: 0,
          memoSavedAt: null,
          version: 0,
          savedAt: '2026-08-11T04:00:00Z',
        },
      ],
      summary: {
        totalCount: 1,
        checkedCount: 0,
        goodCount: 0,
        cautionCount: 0,
        unconfirmedCount: 1,
      },
    },
    {
      stage: 'ON_SITE',
      sourceChecklistId: 7,
      checklistName: '집에서 확인 사본',
      items: [
        {
          visitItemId: 502,
          origin: 'PROVIDED',
          sourceChecklistItemId: 702,
          sourceCheckItemId: 102,
          question: '창문을 열고 소음을 확인했나요?',
          guide: '낮과 밤의 소음이 다를 수 있어요.',
          order: 1,
          status: 'GOOD',
          statusVersion: 2,
          statusSavedAt: '2026-08-11T04:01:00Z',
          inlineMemo: '밤 소음도 다시 확인',
          memoVersion: 1,
          memoSavedAt: '2026-08-11T04:01:30Z',
          version: 2,
          savedAt: '2026-08-11T04:01:00Z',
        },
        {
          visitItemId: 503,
          origin: 'CUSTOM',
          sourceChecklistItemId: 703,
          sourceCheckItemId: null,
          question: '수압은 내 기준에 괜찮은가?',
          guide: null,
          order: 2,
          status: 'UNCONFIRMED',
          statusVersion: 0,
          statusSavedAt: '2026-08-11T04:00:00Z',
          inlineMemo: '',
          memoVersion: 0,
          memoSavedAt: null,
          version: 0,
          savedAt: '2026-08-11T04:00:00Z',
        },
      ],
      summary: {
        totalCount: 2,
        checkedCount: 1,
        goodCount: 1,
        cautionCount: 0,
        unconfirmedCount: 1,
      },
    },
  ],
  summary: visitSummaryFixture,
};

export const visitPageFixture = (content: unknown[], page = 0, hasNext = false) => ({
  content,
  page,
  size: 20,
  totalElements: content.length + (hasNext ? 1 : 0),
  totalPages: hasNext ? page + 2 : page + 1,
  hasNext,
});
